FROM node:16-alpine 

# CREATE APP FOLDER
WORKDIR /app

# GET ARGUMENTS FOR BUILD
ARG APPLICATION_NAME_ARG
ARG PORT_ARG

# PASS ARG's TO ENV FOR PERSIST AFTER BUILD
ENV APPLICATION_NAME=$APPLICATION_NAME_ARG
ENV PORT=$PORT_ARG

# COPY FILES TO APP FOLDER IN CONTAINER
COPY package*.json .
COPY yarn.lock .
COPY server.js .

# INSTALL DEPENDENCIES
RUN yarn install

# RUN THE APP
ENTRYPOINT [ "node", "server.js" ]